<?= $this->doctype() ?>

<html lang="fr">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('MotoRENTautO')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.png'])
            
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/monStyle.css'))

        ?>
        
        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <!--HEADER-->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="<?= $this->url('home') ?>"><img src="img/logo_final.png"/></a>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav">
                        <li><a href="<?= $this->url('home') ?>">Garage</a></li>
                        <li><a href="<?= $this->url('about') ?>">À propos</a></li>
                        <li><a href="<?= $this->url('contact') ?>">Nous contacter</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!--CONTENT-->
        <div class="container-fluid text-center" id="corps">    
            <div class="row content">
                <div class="col-sm-2 sidenav">
                    <!--<p><a href="#">PUB</a></p>-->
                </div>
                <div class="col-sm-8 text-left"> 
                    <h1>Bienvenue</h1>
                    <p>Le garage MotoRENTautO vous propose une large gamme de véhicules et motos pret à être louée.</p>
                    <hr>
                    <?= $this->content ?>
                </div>
            </div>
        </div>
        <!--FOOTER-->
        <footer id="pied">
            <p>&copy; 2017 - <?= date('Y') ?> par MotoRENTautO. Tous droits réservés.</p>
        </footer>
        <?= $this->inlineScript() ?>
    </body>
</html>
